"""v2 resolution-centric schema

Revision ID: 907976775cac
Revises: 
Create Date: 2026-08-12 01:11:42.463235
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '907976775cac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('meeting_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('committee_type', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('agenda_template_id', sa.String(), nullable=True),
    sa.Column('cadence', sa.String(), nullable=True),
    sa.Column('next_meeting_date', sa.Date(), nullable=True),
    sa.Column('member_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_series_org_id'), 'meeting_series', ['org_id'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_department', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_org_id'), 'person', ['org_id'], unique=False)
    op.create_table('agenda_draft',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('target_meeting_date', sa.Date(), nullable=True),
    sa.Column('target_sequence_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_draft_series_id'), 'agenda_draft', ['series_id'], unique=False)
    op.create_table('meeting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('audio_uri', sa.String(), nullable=True),
    sa.Column('source_kind', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pipeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_series_id'), 'meeting', ['series_id'], unique=False)
    op.create_index(op.f('ix_meeting_status'), 'meeting', ['status'], unique=False)
    op.create_table('person_alias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'alias', name='uq_person_alias')
    )
    op.create_index(op.f('ix_person_alias_alias'), 'person_alias', ['alias'], unique=False)
    op.create_index(op.f('ix_person_alias_person_id'), 'person_alias', ['person_id'], unique=False)
    op.create_table('qa_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_log_series_id'), 'qa_log', ['series_id'], unique=False)
    op.create_table('transcript_segment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('speaker_label', sa.String(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segment_meeting_id'), 'transcript_segment', ['meeting_id'], unique=False)
    op.create_table('resolution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('ref_no', sa.String(), nullable=True),
    sa.Column('origin_meeting_id', sa.UUID(), nullable=True),
    sa.Column('origin_segment_id', sa.UUID(), nullable=True),
    sa.Column('origin_agenda_item', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('proposer_person_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('original_due_date', sa.Date(), nullable=True),
    sa.Column('postpone_count', sa.Integer(), nullable=True),
    sa.Column('closed_meeting_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_meeting_id'], ['meeting.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_meeting_id'], ['meeting.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_segment_id'], ['transcript_segment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposer_person_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['resolution.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_series_id'), 'resolution', ['series_id'], unique=False)
    op.create_index(op.f('ix_resolution_status'), 'resolution', ['status'], unique=False)
    op.create_table('agenda_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agenda_draft_id', sa.UUID(), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('resolution_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_draft_id'], ['agenda_draft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolution.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_item_agenda_draft_id'), 'agenda_item', ['agenda_draft_id'], unique=False)
    op.create_table('outbound_action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('resolution_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('recipient_person_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_person_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_action_series_id'), 'outbound_action', ['series_id'], unique=False)
    op.create_index(op.f('ix_outbound_action_status'), 'outbound_action', ['status'], unique=False)
    op.create_table('proposal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('resolution_id', sa.UUID(), nullable=True),
    sa.Column('proposed_status', sa.String(), nullable=True),
    sa.Column('speaker_label', sa.String(), nullable=True),
    sa.Column('candidate_person_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_start_ms', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_meeting_id'), 'proposal', ['meeting_id'], unique=False)
    op.create_table('resolution_assignee',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resolution_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resolution_id', 'person_id', name='uq_resolution_assignee')
    )
    op.create_index(op.f('ix_resolution_assignee_resolution_id'), 'resolution_assignee', ['resolution_id'], unique=False)
    op.create_table('resolution_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resolution_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_meeting_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_meeting_id'], ['meeting.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_history_resolution_id'), 'resolution_history', ['resolution_id'], unique=False)
    op.create_table('resolution_link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resolution_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_start_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_link_meeting_id'), 'resolution_link', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_resolution_link_resolution_id'), 'resolution_link', ['resolution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_link_resolution_id'), table_name='resolution_link')
    op.drop_index(op.f('ix_resolution_link_meeting_id'), table_name='resolution_link')
    op.drop_table('resolution_link')
    op.drop_index(op.f('ix_resolution_history_resolution_id'), table_name='resolution_history')
    op.drop_table('resolution_history')
    op.drop_index(op.f('ix_resolution_assignee_resolution_id'), table_name='resolution_assignee')
    op.drop_table('resolution_assignee')
    op.drop_index(op.f('ix_proposal_meeting_id'), table_name='proposal')
    op.drop_table('proposal')
    op.drop_index(op.f('ix_outbound_action_status'), table_name='outbound_action')
    op.drop_index(op.f('ix_outbound_action_series_id'), table_name='outbound_action')
    op.drop_table('outbound_action')
    op.drop_index(op.f('ix_agenda_item_agenda_draft_id'), table_name='agenda_item')
    op.drop_table('agenda_item')
    op.drop_index(op.f('ix_resolution_status'), table_name='resolution')
    op.drop_index(op.f('ix_resolution_series_id'), table_name='resolution')
    op.drop_table('resolution')
    op.drop_index(op.f('ix_transcript_segment_meeting_id'), table_name='transcript_segment')
    op.drop_table('transcript_segment')
    op.drop_index(op.f('ix_qa_log_series_id'), table_name='qa_log')
    op.drop_table('qa_log')
    op.drop_index(op.f('ix_person_alias_person_id'), table_name='person_alias')
    op.drop_index(op.f('ix_person_alias_alias'), table_name='person_alias')
    op.drop_table('person_alias')
    op.drop_index(op.f('ix_meeting_status'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_series_id'), table_name='meeting')
    op.drop_table('meeting')
    op.drop_index(op.f('ix_agenda_draft_series_id'), table_name='agenda_draft')
    op.drop_table('agenda_draft')
    op.drop_index(op.f('ix_person_org_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_meeting_series_org_id'), table_name='meeting_series')
    op.drop_table('meeting_series')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('organization')
    # ### end Alembic commands ###
